/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rwt_sink.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e38d8ee6b181ee100b84f5ae59bfbcc6)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <rwt/rwt_base_block.h>
// pydoc.h is automatically generated in the build directory
#include <rwt_base_block_pydoc.h>

void bind_rwt_base_block(py::module& m)
{

    using rwt_base_block = gr::rwt::rwt_base_block;


    py::class_<rwt_base_block,
	    gr::sync_block,
        gr::block,
        gr::basic_block,
        std::shared_ptr<rwt_base_block>>(m, "rwt_base_block", D(rwt_base_block))

        .def("set_config", &rwt_base_block::set_config, py::arg("key"), py::arg("value"))

        ;




}








